# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'archive.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(900, 600)
        Dialog.setStyleSheet("QDialog {\n"
"    background-image: url(\"C:/Users/anama/Desktop/k.jpg\");\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"   background-size: 100% 100%\n"
"}")
        self.lineComposer = QtWidgets.QLineEdit(Dialog)
        self.lineComposer.setGeometry(QtCore.QRect(130, 70, 141, 31))
        self.lineComposer.setObjectName("lineComposer")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 901, 51))
        self.label.setObjectName("label")
        self.lineComposition = QtWidgets.QLineEdit(Dialog)
        self.lineComposition.setGeometry(QtCore.QRect(650, 70, 141, 31))
        self.lineComposition.setObjectName("lineComposition")
        self.lineMovement = QtWidgets.QLineEdit(Dialog)
        self.lineMovement.setGeometry(QtCore.QRect(130, 120, 141, 31))
        self.lineMovement.setObjectName("lineMovement")
        self.lineSource = QtWidgets.QLineEdit(Dialog)
        self.lineSource.setGeometry(QtCore.QRect(130, 170, 141, 31))
        self.lineSource.setObjectName("lineSource")
        self.lineTranscriber = QtWidgets.QLineEdit(Dialog)
        self.lineTranscriber.setGeometry(QtCore.QRect(650, 170, 141, 31))
        self.lineTranscriber.setObjectName("lineTranscriber")
        self.lineCatalog = QtWidgets.QLineEdit(Dialog)
        self.lineCatalog.setGeometry(QtCore.QRect(130, 220, 141, 31))
        self.lineCatalog.setObjectName("lineCatalog")
        self.lineSeconds = QtWidgets.QLineEdit(Dialog)
        self.lineSeconds.setGeometry(QtCore.QRect(650, 220, 141, 31))
        self.lineSeconds.setObjectName("lineSeconds")
        self.btnAdd = QtWidgets.QPushButton(Dialog)
        self.btnAdd.setGeometry(QtCore.QRect(40, 280, 121, 31))
        self.btnAdd.setObjectName("btnAdd")
        self.btnUpdate = QtWidgets.QPushButton(Dialog)
        self.btnUpdate.setGeometry(QtCore.QRect(270, 280, 121, 31))
        self.btnUpdate.setObjectName("btnUpdate")
        self.btnDelete = QtWidgets.QPushButton(Dialog)
        self.btnDelete.setGeometry(QtCore.QRect(700, 280, 121, 31))
        self.btnDelete.setObjectName("btnDelete")
        self.tableMusic = QtWidgets.QTableWidget(Dialog)
        self.tableMusic.setGeometry(QtCore.QRect(10, 350, 881, 231))
        self.tableMusic.setStyleSheet("QDialog {\n"
"    background-image: url(\"C:/Users/anama/Desktop/a.jpg\");\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"    background-origin: content;\n"
"    background-size: cover;\n"
"}\n"
"")
        self.tableMusic.setObjectName("tableMusic")
        self.tableMusic.setColumnCount(8)
        self.tableMusic.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableMusic.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableMusic.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableMusic.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableMusic.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableMusic.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableMusic.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableMusic.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableMusic.setHorizontalHeaderItem(7, item)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 70, 91, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 120, 91, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(30, 170, 91, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(30, 220, 71, 31))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(540, 70, 91, 31))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(540, 120, 91, 31))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(540, 170, 101, 31))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(540, 220, 91, 31))
        self.label_9.setObjectName("label_9")
        self.lineEnsemble = QtWidgets.QLineEdit(Dialog)
        self.lineEnsemble.setGeometry(QtCore.QRect(650, 120, 141, 31))
        self.lineEnsemble.setText("")
        self.lineEnsemble.setObjectName("lineEnsemble")
        self.btnSearch = QtWidgets.QPushButton(Dialog)
        self.btnSearch.setGeometry(QtCore.QRect(490, 280, 121, 31))
        self.btnSearch.setObjectName("btnSearch")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Composer Archive System</span></p></body></html>"))
        self.btnAdd.setText(_translate("Dialog", "+Add"))
        self.btnUpdate.setText(_translate("Dialog", "Update"))
        self.btnDelete.setText(_translate("Dialog", "Delete"))
        item = self.tableMusic.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Composer"))
        item = self.tableMusic.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Composition"))
        item = self.tableMusic.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Movement"))
        item = self.tableMusic.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Ensemble"))
        item = self.tableMusic.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Source"))
        item = self.tableMusic.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Transcriber"))
        item = self.tableMusic.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "Catalog"))
        item = self.tableMusic.horizontalHeaderItem(7)
        item.setText(_translate("Dialog", "Seconds"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:9pt;\">Composer:</span></p></body></html>"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:9pt;\">Movement:</span></p></body></html>"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:9pt;\">Source:</span></p></body></html>"))
        self.label_5.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:9pt;\">Catalog:</span></p></body></html>"))
        self.label_6.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:9pt;\">Composition:</span></p></body></html>"))
        self.label_7.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:9pt;\">Ensemble:</span></p></body></html>"))
        self.label_8.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:9pt;\">Transcriber:</span></p></body></html>"))
        self.label_9.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:9pt;\">Seconds:</span></p></body></html>"))
        self.btnSearch.setText(_translate("Dialog", "Search"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())